version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: maco_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: maco
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: maco_phpmyadmin
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: Root@1234
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: maco_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - MYSQL_HOST=mysql-db
    depends_on:
      - mysql-db
    command: npx nodemon server.js
    restart: unless-stopped

  frontend:
    build: .
    container_name: maco_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped

volumes:
  mysql_data:
